docs: consolidate documentation
sparkbox/sparkpress-wordpress-starter pull request #104
Opened 2023-10-20 21:33 UTC by dustin-jw

## Description

This moves nearly all of the documentation into the `README` to make scanning for info easier for developers using the template. This also fixes some inaccuracies, adds some context about things that were under-documented, and adds info for people using the starter template for how to customize it for their projects.

While updating the docs about permalinks, I fixed an issue that broke pagination for custom URL structures, and I renamed the `sparkpress-standard.xml` rule definitions file to reduce the total number of things a developer would need to update when using the starter template. These changes are technically out of scope, but relatively small changes, so it seemed better to include them here rather than split them into different PRs where we'd have to update the docs multiple times.

Closes #91

## To Validate

1. Make sure all PR Checks have passed
2. Pull down this branch
3. Run `npm start`
4. Check that the updated pagination instructions work as expected, and you don't get a 404 response for page 2 of results
5. Change your `.vscode/settings.json` if you have one to point to the `phpcs-rules-standard.xml` file instead of `sparkpress-standard.xml` and confirm that you see linting warnings in VS Code if you intentionally introduce an issue
6. Check the updated `README`, `CONTRIBUTING.md`, and `CODE_OF_CONDUCT.md` files for accuracy and thoroughness

2023-10-23 20:44 UTC, rise-erpelding requested changes
This is great! There were a few minor changes in the `README` that I pointed out that would need to be fixed, and I'll probably take another look through just to make sure there wasn't anything else that stands out.

Linting seems to work ok after changing the name of the php standards file, but running `npm run lint` keeps stopping my Docker container whereas it doesn't for me on `main` (with the previous `settings.json` settings). Does this happen for you too? I am a little puzzled as to why this might be happening.

Otherwise, all looks good!

2023-10-23 20:46 UTC, rise-erpelding commented on README.md
> +1. Go to `http://locahost:8000` to ensure the home page loads
```suggestion
1. Go to `http://localhost:8000` to ensure the home page loads
```

2023-10-23 21:21 UTC, dustin-jw commented on README.md
> +The `scss/` directory holds our styles for the site which are written using [Sass][sass] and follows a modified [BEMIT][bemit] approach to naming and organizing. `stylelint` is used to check that SCS
I think it was missing from the original docs too, now that I look at it, but added one!

2023-10-23 21:22 UTC, dustin-jw commented on README.md
> +   ![Pantheon Development Mode](_assets/pantheon-development-mode.png)
It was, didn't realize it was included twice, good catch!

2023-10-23 21:23 UTC, dustin-jw commented
> Linting seems to work ok after changing the name of the php standards file, but running `npm run lint` keeps stopping my Docker container whereas it doesn't for me on `main` (with the previous `settings.json` settings). Does this happen for you too? I am a little puzzled as to why this might be happening.

Turns out the `--abort-on-container-exit` flag was the issue, but we don't actually need it with the `|| docker compose down` that got added after the flag.

2023-10-24 18:15 UTC, jonoliver commented on src/php/functions.php
> +function normalize_pagination_query_stings( $query_string ) {
```suggestion
function normalize_pagination_query_strings( $query_string ) {
```

2023-10-24 18:15 UTC, jonoliver commented on src/php/functions.php
> +add_filter( 'request', 'normalize_pagination_query_stings' );
```suggestion
add_filter( 'request', 'normalize_pagination_query_strings' );
```
This typo stings! 🐝

2023-10-24 18:29 UTC, dustin-jw commented on README.md
> +	"phpcs.standard": "wp-configs/sparkpress-standard.xml",
Updated in https://github.com/sparkbox/sparkpress-wordpress-starter/pull/104/commits/ce088f9af0eb44bf6b66f313b2899371275da644

2023-10-24 19:43 UTC, rise-erpelding approved these changes

2023-10-24 20:07 UTC, merged